import type {
  AppHealthLog,
  MetricsDaily,
  Plan,
  Profile,
  Signal,
  Subscription,
} from "@/lib/types";
import { getRiskRewardRatio } from "@/lib/trading";

export const demoProfile: Profile = {
  id: "profile-admin-1",
  display_name: "Noble Trader",
  role: "admin",
  email: "admin@redcandle.app",
};

export const demoSubscription: Subscription = {
  id: "sub-1",
  user_id: "profile-admin-1",
  plan: "pro",
  active: true,
  valid_until: "2026-06-01T00:00:00.000Z",
  payment_provider: "paystack",
  payment_reference: "RDC-2026-APR-PRO",
};

export const pricingPlans: Plan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "KES 3,500",
    cadence: "monthly",
    summary: "For active traders who want verified daily setups and Telegram delivery.",
    features: [
      "Live signal feed",
      "Telegram channel access",
      "Rolling 30-day analytics",
      "Member dashboard",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "KES 8,900",
    cadence: "monthly",
    summary: "Best for serious subscribers who want the full history, analytics, and platform edge.",
    features: [
      "Everything in Starter",
      "Full historical library",
      "Symbol analytics",
      "Premium member support",
    ],
  },
  {
    id: "desk",
    name: "Desk",
    price: "KES 24,000",
    cadence: "monthly",
    summary: "A higher-trust tier for teams or prop-style environments that need operational oversight.",
    features: [
      "Everything in Pro",
      "Operational health visibility",
      "Priority onboarding",
      "Admin-ready export access",
    ],
  },
];

export const seedSignals: Signal[] = [
  {
    id: "sig-1",
    slug: "eurusd-long-2026-04-24",
    symbol: "EURUSD",
    asset_class: "forex",
    direction: "long",
    entry_type: "market",
    entry_price: 1.0832,
    take_profit: 1.0894,
    stop_loss: 1.0801,
    timeframe: "H1",
    notes: "London momentum continuation after reclaim of intraday VWAP.",
    status: "closed",
    result: "tp_hit",
    realized_pips: 62,
    risk_reward_ratio: getRiskRewardRatio("long", 1.0832, 1.0894, 1.0801, "EURUSD"),
    created_at: "2026-04-24T06:15:00.000Z",
    updated_at: "2026-04-24T08:40:00.000Z",
    opened_at: "2026-04-24T06:15:00.000Z",
    closed_at: "2026-04-24T08:40:00.000Z",
    created_by: demoProfile.id,
  },
  {
    id: "sig-2",
    slug: "gbpusd-short-2026-04-24",
    symbol: "GBPUSD",
    asset_class: "forex",
    direction: "short",
    entry_type: "pending",
    entry_price: 1.2688,
    take_profit: 1.2629,
    stop_loss: 1.2717,
    timeframe: "H1",
    notes: "Sell limit into failed NY premarket sweep.",
    status: "closed",
    result: "sl_hit",
    realized_pips: -29,
    risk_reward_ratio: getRiskRewardRatio("short", 1.2688, 1.2629, 1.2717, "GBPUSD"),
    created_at: "2026-04-24T09:10:00.000Z",
    updated_at: "2026-04-24T11:05:00.000Z",
    opened_at: "2026-04-24T09:30:00.000Z",
    closed_at: "2026-04-24T11:05:00.000Z",
    created_by: demoProfile.id,
  },
  {
    id: "sig-3",
    slug: "xauusd-long-2026-04-24",
    symbol: "XAUUSD",
    asset_class: "commodities",
    direction: "long",
    entry_type: "market",
    entry_price: 2360.4,
    take_profit: 2376.1,
    stop_loss: 2354.7,
    timeframe: "M30",
    notes: "Momentum continuation with tight risk after opening range reclaim.",
    status: "open",
    result: "open",
    realized_pips: null,
    risk_reward_ratio: getRiskRewardRatio("long", 2360.4, 2376.1, 2354.7, "XAUUSD"),
    created_at: "2026-04-24T12:20:00.000Z",
    updated_at: "2026-04-24T12:20:00.000Z",
    opened_at: "2026-04-24T12:20:00.000Z",
    closed_at: null,
    created_by: demoProfile.id,
  },
  {
    id: "sig-4",
    slug: "btcusdt-long-2026-04-24",
    symbol: "BTCUSDT",
    asset_class: "crypto",
    direction: "long",
    entry_type: "pending",
    entry_price: 68450,
    take_profit: 69620,
    stop_loss: 67920,
    timeframe: "H4",
    notes: "Pending breakout continuation above overnight compression.",
    status: "pending",
    result: "open",
    realized_pips: null,
    risk_reward_ratio: getRiskRewardRatio("long", 68450, 69620, 67920, "BTCUSDT"),
    created_at: "2026-04-24T14:00:00.000Z",
    updated_at: "2026-04-24T14:00:00.000Z",
    opened_at: null,
    closed_at: null,
    created_by: demoProfile.id,
  },
];

export const metricsDaily: MetricsDaily[] = [
  {
    date: "2026-04-22",
    trades_count: 4,
    wins: 3,
    losses: 1,
    win_rate: 75,
    expectancy_pips: 18.4,
    profit_factor: 2.4,
    max_drawdown: 26,
    sharpe: 1.08,
    sortino: 1.74,
  },
  {
    date: "2026-04-23",
    trades_count: 3,
    wins: 2,
    losses: 1,
    win_rate: 66.7,
    expectancy_pips: 15.2,
    profit_factor: 1.98,
    max_drawdown: 31,
    sharpe: 0.94,
    sortino: 1.5,
  },
  {
    date: "2026-04-24",
    trades_count: 2,
    wins: 1,
    losses: 1,
    win_rate: 50,
    expectancy_pips: 16.5,
    profit_factor: 2.14,
    max_drawdown: 29,
    sharpe: 0.81,
    sortino: 1.2,
  },
];

export const healthLogs: AppHealthLog[] = [
  {
    id: "health-1",
    checked_at: "2026-04-24T10:00:00.000Z",
    vercel_status: "healthy",
    supabase_status: "degraded",
    telegram_status: "healthy",
    billing_status: "healthy",
    api_latency_ms: 184,
    error_rate: 0.7,
  },
  {
    id: "health-2",
    checked_at: "2026-04-24T10:05:00.000Z",
    vercel_status: "healthy",
    supabase_status: "healthy",
    telegram_status: "healthy",
    billing_status: "healthy",
    api_latency_ms: 142,
    error_rate: 0.2,
  },
  {
    id: "health-3",
    checked_at: "2026-04-24T10:10:00.000Z",
    vercel_status: "healthy",
    supabase_status: "healthy",
    telegram_status: "healthy",
    billing_status: "healthy",
    api_latency_ms: 137,
    error_rate: 0.1,
  },
];
